### ISSUE TITLE
AttributeError: module 'dal.autocomplete' has no attribute 'ModelSelect2'

### ISSUE THREAD

**Issue by mike-johnson-jr** [yourlabs/django-autocomplete-light#1043]
**versions tried: 3.3.0, 3.2.0, 3.2.3, 2.2.10**

Full traceback:
    Traceback (most recent call last):
      File "manage.py", line 15, in <module>
        execute_from_command_line(sys.argv)
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site- 
   packages\django\core\management\__init__.py", line 363, in execute_from_command_line
        utility.execute()
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site- 
   packages\django\core\management\__init__.py", line 337, in execute
        django.setup()
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site-packages\django\__init__.py", line 27, in 
    setup
        apps.populate(settings.INSTALLED_APPS)
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site-packages\django\apps\registry.py", line 
    116, in populate
        app_config.ready()
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site- 
   packages\django\contrib\admin\apps.py", line 23, in ready
        self.module.autodiscover()
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site- 
   packages\django\contrib\admin\__init__.py", line 26, in autodiscover
        autodiscover_modules('admin', register_to=site)
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site- 
   packages\django\utils\module_loading.py", line 50, in autodiscover_modules
        import_module('%s.%s' % (app_config.name, module_to_search))
      File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site-packages\powerdns\admin.py", line 6, in   
    <module>
        from powerdns.forms import (
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site-packages\powerdns\forms.py", line 13, in 
    <module>
        class RecordForm(forms.ModelForm):
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site-packages\powerdns\forms.py", line 14, in 
    RecordForm
        class Meta:
      File "C:\Users\Michael\projects\bosnet\bosnetvenv\lib\site-packages\powerdns\forms.py", line 21, in   
    Meta
        'owner': autocomplete.ModelSelect2(
    AttributeError: module 'dal.autocomplete' has no attribute 'ModelSelect2'
`

**This is inside a package that I'm using. I forked and am editing it. Can anyone help with this error? Thanks in advance.**

**Comment by mike-johnson-jr** [comment]
needed to add 'dal' and 'dal_select2' to settings.INSTALLED_APPS

**Comment by YesThat** [comment]
You..  are awesome.  Thank you so much for sharing that.  Talk about a vague error.

**Comment by jpic** [comment]
Perhaps you would like to contribute a FAQ entry ?
