### ISSUE TITLE
get_search_results throws an exception when called with a QuerySetSequence (not a QuerySet as usually)

### ISSUE THREAD

**Issue by stoffi92** [yourlabs/django-autocomplete-light#1190]
v3.7.x introduces a get_search_result function in [src/dal/views.py] BaseQuerySetView which (at least in my case) throws an exception when called with a QuerySetSequence (instead of a Queryset):

```
Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/dal/views.py", line 55, in dispatch
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "venv/lib/python3.7/site-packages/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "venv/lib/python3.7/site-packages/dal_queryset_sequence/views.py", line 47, in get_queryset
    qs = super(BaseQuerySetSequenceView, self).get_queryset()
  File "venv/lib/python3.7/site-packages/dal/views.py", line 106, in get_queryset
    qs = self.get_search_results(qs, self.q)
  File "venv/lib/python3.7/site-packages/dal/views.py", line 146, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
TypeError: filter() takes 1 positional argument but 2 were given

```

**Comment by jpic** [comment]
Thank you for reporting, a fix targets next minor release #1199
