### ISSUE TITLE
Please add Django 1.7 compatibility

### ISSUE THREAD

**Issue by lorddaedra** [yourlabs/django-autocomplete-light#247]
```python3
(bemyco3) iMac-Alexander:bemyco lorddaedra$ ./manage.py
Traceback (most recent call last):
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/autocomplete_light/registry.py", line 205, in __getitem__
    return super(AutocompleteRegistry, self).__getitem__(name)
KeyError: 'CityAutocomplete'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
    utility.execute()
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/core/management/__init__.py", line 391, in execute
    django.setup()
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/apps/registry.py", line 111, in populate
    app_config.ready()
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/lorddaedra/Projects/bemyco/bemycobase/admin.py", line 5, in <module>
    from bemycobase.forms import UserCreationForm, UserChangeForm
  File "/Users/lorddaedra/Projects/bemyco/bemycobase/forms.py", line 15, in <module>
    class SignupForm(SignupFormBase):
  File "/Users/lorddaedra/Projects/bemyco/bemycobase/forms.py", line 22, in SignupForm
    city = autocomplete_light.ModelChoiceField('CityAutocomplete')
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/autocomplete_light/fields.py", line 24, in __init__
    widget)
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/autocomplete_light/fields.py", line 45, in get_autocomplete
    return registry.get_autocomplete_from_arg(autocomplete)
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/autocomplete_light/registry.py", line 211, in get_autocomplete_from_arg
    return self[arg]
  File "/Users/lorddaedra/Envs/bemyco3/lib/python3.3/site-packages/autocomplete_light/registry.py", line 207, in __getitem__
    raise AutocompleteNotRegistered(name, self)
autocomplete_light.exceptions.AutocompleteNotRegistered: CityAutocomplete not registered (registry is empty)
```

https://docs.djangoproject.com/en/dev/releases/1.7/

**Comment by jpic** [comment]
I think this has been fixed for a long time, closing.
