### ISSUE TITLE
forms using autocomplete prevent initial db migration

### ISSUE THREAD

**Issue by dferrante** [yourlabs/django-autocomplete-light#560]
Hi, I'm using python 2.7 and django 1.9.1.  I'm developing an app, and when I went to install the development version on another computer, running a ./manage.py migrate threw an error because a form field was set as an autocomplete field referencing a AutocompleteModelBase autocompleter.  The model that the autocomplete field referenced had not yet been created as the schema had never been migrated before, and the migrate command threw a 'Table does not exist' error.  Commenting out the field fixed the problem.  I guess the fix would be the library should probably not try to resolve tables during a migration?

**Comment by jpic** [comment]
Very interesting, seems like this project is completely messed up !!

Could you paste the traceback and code ?

Thanks !

**Comment by m-ajay** [comment]
I too have the same problem. Here's the traceback. 
(env) D:\Paie Roll\Source _Copy>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Paie Roll\env\lib\site-packages\django\core\management\__init__.py",
line 350, in execute_from_command_line
    utility.execute()
  File "D:\Paie Roll\env\lib\site-packages\django\core\management\__init__.py",
line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Paie Roll\env\lib\site-packages\django\core\management\base.py", line
 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Paie Roll\env\lib\site-packages\django\core\management\base.py", line
 398, in execute
    self.check()
  File "D:\Paie Roll\env\lib\site-packages\django\core\management\base.py", line
 426, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\Paie Roll\env\lib\site-packages\django\core\checks\registry.py", line
 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\Paie Roll\env\lib\site-packages\django\core\checks\urls.py", line 10,
 in check_url_config
    return check_resolver(resolver)
  File "D:\Paie Roll\env\lib\site-packages\django\core\checks\urls.py", line 19,
 in check_resolver
    for pattern in resolver.url_patterns:
  File "D:\Paie Roll\env\lib\site-packages\django\utils\functional.py", line 33,
 in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Paie Roll\env\lib\site-packages\django\core\urlresolvers.py", line 41
7, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Paie Roll\env\lib\site-packages\django\utils\functional.py", line 33,
 in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Paie Roll\env\lib\site-packages\django\core\urlresolvers.py", line 41
0, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Paie Roll\Source _Copy\paieroll\urls.py", line 19, in <module>
    from employers import urls as employer_urls
  File "D:\Paie Roll\Source _Copy\employers\urls.py", line 3, in <module>
    from . import views
  File "D:\Paie Roll\Source _Copy\employers\views.py", line 31, in <module>
    from employees.forms import EmployeeForm
  File "D:\Paie Roll\Source _Copy\employees\forms.py", line 10, in <module>
    class EmployeeForm(forms.ModelForm):
  File "D:\Paie Roll\Source _Copy\employees\forms.py", line 25, in EmployeeForm
    class Meta:
  File "D:\Paie Roll\Source _Copy\employees\forms.py", line 123, in Meta
    'min': ProvincialTaxLookup.objects.get_min_slab().salary_upper_limit,
  File "D:\Paie Roll\Source _Copy\common\models\taxes.py", line 34, in get_min_s
lab
    return self.all().order_by('salary_lower_limit').first()
  File "D:\Paie Roll\env\lib\site-packages\django\db\models\query.py", line 550,
 in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "D:\Paie Roll\env\lib\site-packages\django\db\models\query.py", line 258,
 in __iter__
    self._fetch_all()
  File "D:\Paie Roll\env\lib\site-packages\django\db\models\query.py", line 1074
, in _fetch_all
    self._result_cache = list(self.iterator())
  File "D:\Paie Roll\env\lib\site-packages\django\db\models\query.py", line 52,
in __iter__
    results = compiler.execute_sql()
  File "D:\Paie Roll\env\lib\site-packages\django\db\models\sql\compiler.py", li
ne 852, in execute_sql
    cursor.execute(sql, params)
  File "D:\Paie Roll\env\lib\site-packages\django\db\backends\utils.py", line 79
, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\Paie Roll\env\lib\site-packages\django\db\backends\utils.py", line 64
, in execute
    return self.cursor.execute(sql, params)
  File "D:\Paie Roll\env\lib\site-packages\django\db\utils.py", line 95, in __ex
it__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\Paie Roll\env\lib\site-packages\django\db\backends\utils.py", line 64
, in execute
    return self.cursor.execute(sql, params)
  File "D:\Paie Roll\env\lib\site-packages\django\db\backends\mysql\base.py", li
ne 112, in execute
    return self.cursor.execute(query, args)
  File "C:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defau
lterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'paieroll-test.common_provincial
taxlookup' doesn't exist")
