### ISSUE TITLE
Error after updating the to the latest version

### ISSUE THREAD

**Issue by subramanyamVemu** [yourlabs/django-autocomplete-light#587]
Hi

After updating to the latest version we get the following error

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bala/.virtualenvs/modetwoenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/bala/.virtualenvs/modetwoenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/bala/.virtualenvs/modetwoenv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/bala/.virtualenvs/modetwoenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/bala/.virtualenvs/modetwoenv/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named autocomplete_light

Bala

**Comment by jpic** [comment]
It seems like you upgraded to v3, which is not compatible with v2.

Either upgrade to v3, either pin your requirements to v2, ie: `django-autocomplete-light<3.0.0`

**Comment by jpic** [comment]
Check out how I had setup the requirement for another project, last year, before knowing i'd work on DAL v3: https://github.com/political-memory/political_memory/commit/66980e590766ac54351e926130bd9e3886810388#diff-2eeaed663bd0d25b7e608891384b7298R12

django-autocomplete-light>=2.2,<3.0

Result: not broken by the upgrade :D
