### ISSUE TITLE
ImportError: No module named 'autocomplete_light'

### ISSUE THREAD

**Issue by Copser** [yourlabs/django-autocomplete-light#658]
Hello,

I'm trying to set up a widget that mine colleague send me, and after installing `django-autocomplete-light==3.1.4`, I'm facing this error
```

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/petarp/.virtualenvs/SOCIETE/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/petarp/Documents/Projects/SOCIETE/societe_project/societe/reviews/admin.py", line 4, in <module>
    from reviews.forms import OnMapReviewLayoutForm
  File "/home/petarp/Documents/Projects/SOCIETE/societe_project/societe/reviews/forms.py", line 1, in <module>
    import autocomplete_light
ImportError: No module named 'autocomplete_light'
```
`django version == 1.8.7`
`python version == 3.4.3`

This is what I'm using in mine project. I have tried to manually import `autocomplete_light` module in python shell, but 
```
Python 3.4.3 (default, Oct 14 2015, 20:33:09) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import autocomplete_light
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'autocomplete_light'
>>>
``` 
I have read similar posts in issues but they didn't help, is there something I'm missing?
Thanks.

**Comment by jpic** [comment]
>=3.0 doesn't have BC for v2. Either pin your requirements, either upgrade your code to v3.
