### ISSUE TITLE
ModelChoiceField label_from_instance is ignored

### ISSUE THREAD

**Issue by AbsoluteDestiny** [yourlabs/django-autocomplete-light#685]
#607 was closed but when using v3.1.5 on Django 1.9.6 `label_from_instance` is never called and only the `__str__` representation is shown.

**Comment by jpic** [comment]
Well we can't call the label_from_instance method from the view at this point because the view doesn't have neither the form nor the form field object.

We could call it on form rendering though, if it's not already the case.

Thoughts ?

**Comment by jpic** [comment]
Any suggestion you would like to suggest ? ;)

**Comment by jpic** [comment]
Should we let the user pass a widget class to the autocomplete view so that it reuses the label_for_instance method ?

**Comment by AbsoluteDestiny** [comment]
I don't really know enough about how your code works to suggest solutions other than to have some way of being able to choose how the autocomplete result is displayed based on the model instance - whether that is a widget class or some other method.

**Comment by jpic** [comment]
Doesn't run for me:

```

[te] 18/10 2016 00:23:49 jpic@lue /tmp/test  (master)
$ python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7fbadfeca230>
Traceback (most recent call last):
  File "/tmp/test/te/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/tmp/test/te/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/tmp/test/te/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/tmp/test/te/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/tmp/test/te/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/tmp/test/te/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/tmp/test/te/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named datetimewidget
^C
```

Even after removing pyodb and pyodb azure from requirements and installing them. 

Could you try to reproduce the issue in a minimal project please ? The best is to fork test_project and reproduce it in a new app there

Thanks
