### ISSUE TITLE
autocomplete.QuerySetSequenceModelField and unique_together

### ISSUE THREAD

**Issue by bashu** [yourlabs/django-autocomplete-light#689]
Hey,

I have modified ``test_project/selec2_generic_foreign_key/models.py``:
```python
class TestModel(models.Model):
    ...
    class Meta:
        unique_together = ['name', 'content_type', 'object_id']
```

and now after trying to save new object:
```python
Traceback (most recent call last):
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1378, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/contrib/admin/options.py", line 991, in save_model
    obj.save()
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/bashu/.virtualenvs/dal/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: select2_generic_foreign_key_testmodel.name, select2_generic_foreign_key_testmodel.content_type_id, select2_generic_foreign_key_testmodel.object_id
```

**Comment by jpic** [comment]
Hi, thanks for your feedback but I could not reproduce your issue.

It works fine for me with

```
diff --git a/test_project/select2_generic_foreign_key/models.py b/test_project/select2_generic_foreign_key/models.py
index d53ee4f..c18b5ce 100644
--- a/test_project/select2_generic_foreign_key/models.py
+++ b/test_project/select2_generic_foreign_key/models.py
@@ -31,3 +31,6 @@ class TestModel(models.Model):

     def __str__(self):
         return self.name
+
+    class Meta:
+        unique_together = ['name', 'content_type', 'object_id']

```

And of course after applying:

```
$ cat select2_generic_foreign_key/migrations/0002_auto_20160517_1839.py
# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select2_generic_foreign_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testmodel',
            unique_together=set([('name', 'content_type', 'object_id')]),
        ),
    ]
```
