### ISSUE TITLE
Generic Foreign Key "the results could not be loaded"

### ISSUE THREAD

**Issue by Areopagitics** [yourlabs/django-autocomplete-light#857]
Hi there,
I have been trying to get a model with 2 Generic Foreign Key fields to work in the Admin with autocomplete...but no luck; I get the error `NotImplementedError: QuerySequence does not implement get_compiler()` in the terminal. The right saved instance is showing up in Admin but none of the others. Any help greatly appreciated.
![capture1](https://cloud.githubusercontent.com/assets/24683841/26753081/5d5b0652-4813-11e7-9784-cb2f528e6ddc.JPG)

my model:
```
class Relation(Owner):
    second_class = models.ForeignKey(ContentType, editable=False, related_name='second_class', on_delete=models.CASCADE, null=True, blank=True,)
    second_id = models.PositiveIntegerField(null=True, blank=True, editable=False,)
    second = GenericForeignKey('second_class', 'second_id') # when 2 objects are involved: values go here, or group persons
    first_class = models.ForeignKey(ContentType, editable=False, related_name='first_class', on_delete=models.CASCADE)
    first_id = models.PositiveIntegerField(editable=False,)
    first = GenericForeignKey('first_class', 'first_id') 
    rank = models.IntegerField(null=True, blank=True,)
```

my form:

```
class RelationAutoForm(autocomplete.FutureModelForm):
    second = autocomplete.QuerySetSequenceModelField(
        queryset=autocomplete.QuerySetSequence(
            Value.objects.all(),
            Definition.objects.all(),
        ),
        required=False,
        widget=autocomplete.QuerySetSequenceSelect2('selectValue_gfk'),
    )
    first = autocomplete.QuerySetSequenceModelField(
        queryset=autocomplete.QuerySetSequence(
            City.objects.all(),
        ),
        required=True,
        widget=autocomplete.QuerySetSequenceSelect2('selectCity_gfk'),
    )
    class Meta:
        model = Relation
```
my urls:

```
url(
        '^selectCity-gfk/$',
        autocomplete.Select2QuerySetSequenceView.as_view(
            queryset=autocomplete.QuerySetSequence(
                City.objects.all(),
            )
        ),
        name='selectCity_gfk',
    ),
    url(
        '^selectValue-gfk/$',
        autocomplete.Select2QuerySetSequenceView.as_view(
            queryset=autocomplete.QuerySetSequence(
                Value.objects.all(),
                Definition.objects.all(),
            )
        ),
        name='selectValue_gfk',
    ),
```

**Comment by jpic** [comment]
We need the complete traceback.

What are you expecting the view to do by default with your queryset ?

Any reason you didn't want to follow the manual ? 

http://django-autocomplete-light.readthedocs.io/en/master/gfk.html#view-example-for-querysetsequence-and-select2

**Comment by Areopagitics** [comment]
thanks jpic! I feel like you should be getting paid for this ... in this capitalist system 👎 .

I followed the example in the demo and which the example in Select2QuerySetSequenceView gives:

```
    Example usage::

        url(
            '^your-generic-autocomplete/$',
            autocomplete.Select2QuerySetSequenceView.as_view(
                queryset=autocomplete.QuerySetSequence(
                    Group.objects.all(),
                    TestModel.objects.all(),
                )
            ),
            name='your-generic-autocomplete',
        )
```
I also tried a simple custom view:

```
class RelationAutocompleteView(Select2QuerySetSequenceView):
    def get_queryset(self):
        cities = City.objects.all()

        qs = QuerySetSequence(cities)

        return qs
```

and changed the urls appropriately:

```
url(
        '^selectCity-gfk/$',
        RelationAutocompleteView.as_view(
            queryset=autocomplete.QuerySetSequence(
                City.objects.all(),
            )
        ),
        name='selectCity_gfk',
    ),
```
but to no avail...
I tested QuerySetSequence in the shell and this seems to be next lead in the error  `NotImplementedError: QuerySequence does not implement get_compiler()`

Oh, I also had some problems earlier with QuerySequence (couldn't find module error) wherever I imported it, until I upgraded django-querysetsequence.

Any more ideas?

**Comment by jpic** [comment]
Don't worry, I'm currently building an ecologic town where everything is open source even the "system" itself with a badass hackerspace, I'm leaving the individualist/capitalist system, I'm not compatible with it, I can't live in a system that's not open source it's like being in a mental prison hahaha

No idea about the get_compiler error, can you post the full traceback please ?
We've got another report of the get_compiler error in #855, i wonder if we need to raise this to django-querysetsequence developers.

**Comment by Areopagitics** [comment]
thanks for getting back again! good luck to your ecologic town...have you heard of the Zeitgeist movement? some interesting ideas...

Here's the traceback:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 226, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 250, in __iter__
    self._fetch_all()
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 1105, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 50, in __iter__
    compiler = queryset.query.get_compiler(using=db)
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\queryset_sequence\_inheritance.py", line 43, in not_impl
    (name, attr))
NotImplementedError: QuerySequence does not implement get_compiler()
```

**Comment by jpic** [comment]
What's the code you executed in console exactly pleas ?
I'd like to reproduce this.

**Comment by Areopagitics** [comment]
here you go! sorry!

```
(InteractiveConsole)
>>> from queryset_sequence import QuerySetSequence
>>> from .models import *
>>> cities = City.objects.all()
>>> qs = QuerySetSequence(cities)
>>> qs
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 226, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 250, in __iter__
    self._fetch_all()
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 1105, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\django\db\models\query.py", line 50, in __iter__
    compiler = queryset.query.get_compiler(using=db)
  File "C:\Users\Areopagitics\Development\env-dev\lib\site-packages\queryset_sequence\_inheritance.py", line 43, in not_impl
    (name, attr))
NotImplementedError: QuerySequence does not implement get_compiler()
```

**Comment by jpic** [comment]
Can you report this on https://github.com/jpic/django-querysetsequence/ please ?

Thanks !

**Comment by Areopagitics** [comment]
One thing I noticed about installing **django-autocomplete-light** is that it doesn't have **django-querysetsequence** as a required module; is there maybe some other module that I am missing for the **get_compiler()**?

**Comment by Areopagitics** [comment]
Problem solved with Django 1.10! Issue [#26](https://github.com/percipient/django-querysetsequence/issues/26) in QuerySequence also has a similar problem.
