### ISSUE TITLE
S2QuerySet - ForeignKey with to_field that is not primary key.

### ISSUE THREAD

**Issue by Peter-Potts** [yourlabs/django-autocomplete-light#873]
Hi YourLabs.
I really appreciate your work on this project. It is a very helpful addition to django!
(I am hoping this is the right way to contribute to your project)

My use case here is a Select2QuerySetView, where I am using a ForeignKey with a 'to_field' parameter - but importantly the to_field is not an IntegerField nor the pk, but a TextField (I am using django with an imported database table).

In my CreateView, I put a custom get_result_value(...) function to return my to_field value.
However I had trouble in my EditView, where it had to show the selected choices back - with:
ValueError: invalid literal for int() with base 10: 'example-string-to_field-value'
pointing to QuerySetSelectMixin.filter_choices_to_render, at "filter(   pk__in = ..."
Of course, it was looking up my to_field (string) as the model pk (which it thought should be an integer, helping me notice it also wasn't the pk).

I came up with a solution that worked for my project, and have provided it below. Hopefully this helps.
I allowed a 'to_field' param on the QuerySetSelectMixin, and used that to construct the filter_choices_to_render filter.

```
class QuerySetSelectMixin(WidgetMixin):
    """QuerySet support for choices."""

    #added (an override of) this method, to accept an optional 'to_field' parameter
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('to_field', 'pk')
        self.to_field_name = kwargs.pop('to_field')
        super().__init__(*args, **kwargs)

    #then use the value here
    def filter_choices_to_render(self, selected_choices):
        """Filter out un-selected choices if choices is a QuerySet."""
        filter_args = { '%s__in'%self.to_field_name : [c for c in selected_choices if c] } #Construct the 'pk__in' part with the chosen to_field name
        self.choices.queryset = self.choices.queryset.filter(
            **filter_args #use the filter
        )
```

(For safe measure, as I was looking through the code, I think the default BaseQuerySetView post function should also use the get_result_value/get_result_label function calls - as these are overwritten in my code) 
```
class BaseQuerySetView(ViewMixin, BaseListView):
    """Base view to get results from a QuerySet.
#....
        def post(self, request):
#...
        return http.JsonResponse({
            'id': self.get_result_value(result), #modified to function call
            'text': self.get_result_label(result), #modified to function call
        })

```

Regards again, I appreciate your work.
Please let me know your thoughts about this, or anything I could do here.
Peter

**Comment by jpic** [comment]
Can you paste the form code please ?

**Comment by Peter-Potts** [comment]
Thanks for your reply.
Apologies, I wasn't originally sure myself what my problem was, but I think it is:
_Using a ForeignKey to_field which points to a field other than the pk._
(The string->int conversion fortunately highlighted this problem)


My models have in effect:

```
#models.py:
class ReferenceModel(models.Model):
    """Imported model made by inspectdb"""
    autofield = models.AutoField(primary_key=True)
    id_string = models.TextField(unique=True)
	
    class Meta:
        managed = False


class MainModel(models.Model):
    """my custom model"""
    #other fields
    reference = models.ForeignKey(
        ReferenceModel, on_delete=models.PROTECT,
        to_field='id_string',
    )

```
	
and the form has:

```
#forms.py
class MainModelCreateAndUpdateForm(forms.ModelForm):
	class Meta:
			model = MainModel
			fields = [
				#...,
				'reference',
			]
			
			widgets = {
				'reference': autocomplete.ModelSelect2(
					url='reference_model_autocomplete',
				),
				#another field also used a standard ModelSelect2Multiple
			}

#views.py
class MainModelUpdateView(MyPermissionMixin, UpdateView):
	form_class = MainModelCreateAndUpdateForm
	#...
```


As the to_field in MainModel.reference is not to the ReferenceModel pk, the lookup failed in ModelSelect2.filter_choices_to_render.
So the code I copied above was how I got around looking up a non-pk field in the model.
[A side note on the database/ReferenceModel: in truth, id_string is the actual postgres pk, but django seems to expect AutoFields have pk=True.]

This would definitely not be a standard use case, though I believe django does let you use a ForeignKey to_field that is unique, even if not pk - so I hoped to provide my solution around this.
For my project, I just made a class ModelSelect2WithToField(ModelSelect2) using that code.


Regards again,
Appreciate your work,
Peter

**Comment by jpic** [comment]
Could you add your complete traceback please ? We'll see what line of code is involved in this exactly then.

**Comment by Peter-Potts** [comment]
Thanks, hopefully this is useful.
Steps:
- I created a MainModel through MainModelCreateView - the ModelSelect2 widget worked perfectly to select eg my_mainmodel_instance.reference <- { my_referencemodel_instance: autofield=1, id_string='EXAMPLE_ID_001' }
[Refresher from the models.py: autofield is the pk, and id_string is my FK to_field]

- Then went to edit the my_mainmodel_instance through MainModelUpdateView, and got:
ValueError: invalid literal for int() with base 10: 'EXAMPLE_ID_001'

From the runserver output:
```
Internal Server Error: /mainmodel/edit/1/
Traceback (most recent call last):
  File "mydir~\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "mydir~\venv\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "mydir~\venv\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "mydir~\venv\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "mydir~\venv\lib\site-packages\django\template\response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "mydir~\venv\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "mydir~\venv\lib\site-packages\django\test\utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "mydir~\venv\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "mydir~\venv\lib\site-packages\django\test\utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "mydir~\venv\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "mydir~\venv\lib\site-packages\django\test\utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "mydir~\venv\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "mydir~\venv\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "mydir~\venv\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "mydir~\venv\lib\site-packages\django\template\base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "mydir~\venv\lib\site-packages\django\utils\encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "mydir~\venv\lib\site-packages\django\utils\html.py", line 385, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "mydir~\venv\lib\site-packages\django\forms\forms.py", line 137, in __str__
    return self.as_table()
  File "mydir~\venv\lib\site-packages\django\forms\forms.py", line 285, in as_table
    errors_on_separate_row=False)
  File "mydir~\venv\lib\site-packages\django\forms\forms.py", line 240, in _html_output
    'field': six.text_type(bf),
  File "mydir~\venv\lib\site-packages\django\utils\html.py", line 385, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "mydir~\venv\lib\site-packages\django\forms\boundfield.py", line 41, in __str__
    return self.as_widget()
  File "mydir~\venv\lib\site-packages\django\forms\boundfield.py", line 127, in as_widget
    **kwargs
  File "mydir~\venv\lib\site-packages\dal\widgets.py", line 150, in render
    widget = super(WidgetMixin, self).render(name, value, attrs)
  File "mydir~\venv\lib\site-packages\django\forms\widgets.py", line 220, in render
    context = self.get_context(name, value, attrs)
  File "mydir~\venv\lib\site-packages\django\forms\widgets.py", line 663, in get_context
    context = super(Select, self).get_context(name, value, attrs)
  File "mydir~\venv\lib\site-packages\django\forms\widgets.py", line 625, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "mydir~\venv\lib\site-packages\dal\widgets.py", line 140, in optgroups
    self.filter_choices_to_render(selected_choices)
  File "mydir~\venv\lib\site-packages\dal\widgets.py", line 183, in filter_choices_to_render
    pk__in=[c for c in selected_choices if c]
  File "mydir~\venv\lib\site-packages\django\db\models\query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "mydir~\venv\lib\site-packages\django\db\models\query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "mydir~\venv\lib\site-packages\django\db\models\sql\query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "mydir~\venv\lib\site-packages\django\db\models\sql\query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "mydir~\venv\lib\site-packages\django\db\models\sql\query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "mydir~\venv\lib\site-packages\django\db\models\sql\query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "mydir~\venv\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "mydir~\venv\lib\site-packages\django\db\models\lookups.py", line 219, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "mydir~\venv\lib\site-packages\django\db\models\fields\__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'EXAMPLE_ID_001'
```

The parts in bold from the debug server page were:
```
  File "mydir~\venv\lib\site-packages\dal\widgets.py", line 150, in render
    widget = super(WidgetMixin, self).render(name, value, attrs)
#and
  File "mydir~\venv\lib\site-packages\dal\widgets.py", line 140, in optgroups
    self.filter_choices_to_render(selected_choices)
  File "mydir~\venv\lib\site-packages\dal\widgets.py", line 183, in filter_choices_to_render
    pk__in=[c for c in selected_choices if c]
```
(at 183, debug context shows: """ selected_choices == ['EXAMPLE_ID_001'] , self ==
 <dal_select2.widgets.ModelSelect2 object at 0x04EACA90>""")


The part of the error I noticed was the mismatch between the filter 'pk__in' from QuerySetSelectMixin.filter_choices_to_render, with the choices list being [to_fields,]
So my workaround was to dynamically create a '%s__in' filter, using an optional __init__ parameter.

PS: django-autocomplete-light==3.2.9, Django==1.11.3

Thanks again,
Please let me know if there is anything else I can help with,
Peter

**Comment by jpic** [comment]
Thanks, can you paste your form code please ? Perhaps using another form field would work better.

**Comment by Peter-Potts** [comment]
Sorry for the delay - what else did you want to see from the form code?
For my project, I made a workaround, just implementing the changes to the QuerySetSelectMixin code I tried to post above in a CustomModelSelect2 class. So I am happy however it goes.
I wasn't sure if this was the right way to do it - I was hoping to share the code I used in case someone else had similar troubles/use case. (Sorry if this was the wrong place to post?)
