### ISSUE TITLE
Encode Error

### ISSUE THREAD

**Issue by thobryan** [yourlabs/django-autocomplete-light#878]
An encode error is being shown when "UTF-8" encode with brazilian accents is in database: 

> 
> Internal Server Error: /ocupacao-autocomplete/
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
>     response = self._get_response(request)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/dal/views.py", line 48, in dispatch
>     return super(ViewMixin, self).dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/list.py", line 176, in get
>     return self.render_to_response(context)
>   File "/usr/local/lib/python2.7/dist-packages/dal_select2/views.py", line 52, in render_to_response
>     'results': self.get_results(context) + create_option,
>   File "/usr/local/lib/python2.7/dist-packages/dal_select2/views.py", line 24, in get_results
>     } for result in context['object_list']
>   File "/usr/local/lib/python2.7/dist-packages/dal/views.py", line 74, in get_result_value
>     return str(result.pk)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 15: ordinal not in range(128)

**Comment by thobryan** [comment]
A branch (issue-878) was created with a correct suggestion. I tested and it worked fine

**Comment by jpic** [comment]
Any reason you don't want to do a branch in your fork meanwhile ?

**Comment by jpic** [comment]
Are on on python2 ? Seems like you can fix it by overriding  get_result_value in your autocomplete view where it's trying to typecast a bytestring to unicode if I understand correctly this is on python2 ?

**Comment by thobryan** [comment]
Hi jpic, I am on python2, the change was pretty simple, in the file:  src/dal/views.py I just removed "str" function on line 74. Since the data should be passed correctly encoded to DAL it's not necessary to use str(). What do you think?

**Comment by jpic** [comment]
It works in your case because it's already a string, and not an integer PK.
Instead of hacking dal source code, i recommend you do this override in your own view.
Otherwise, contribute a fix, perhaps typecast to six.str instead of str or something.

**Comment by c3959** [comment]
How can I overwrite the view to work with the list: [u'José', u'María'] ??

**Comment by jpic** [comment]
@c3959 it's in the tutorial.
