### ISSUE TITLE
Create new choice when using Select2ListView

### ISSUE THREAD

**Issue by apnewberry** [yourlabs/django-autocomplete-light#908]
I'd like to allow the user to create a new choice option, but I'm using a list. Is it possible to do this? If not, what's the nearest alternative? Here's code from the test project. My real `views.py` is below for context.

```python
# select2_list/urls.py

urlpatterns = [
    url(
        'test-autocomplete/$',
        Select2ListViewAutocomplete.as_view(create_field='name'),
        name='select2_list',
    ),
]

```

```python

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe97e0df400>
Traceback (most recent call last):
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/Documents/dal/dal_env/src/django-autocomplete-light/test_project/urls.py", line 17, in <module>
    url(r'^select2_list/', include('select2_list.urls')),
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/user/Documents/dal/dal_env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/Documents/dal/dal_env/src/django-autocomplete-light/test_project/select2_list/urls.py", line 9, in <module>
    Select2ListViewAutocomplete.as_view(create_field='name'),
  File "/home/user/Documents/dal/dal_env/lib/python3.5/site-packages/django/views/generic/base.py", line 59, in as_view
    "attributes of the class." % (cls.__name__, key))
TypeError: Select2ListViewAutocomplete() received an invalid keyword 'create_field'. as_view only accepts arguments that are already attributes of the class.

```

```python
# app/views.py

class NameAutocomplete(autocomplete.Select2ListView):

    def get_list(self):
        return self.forwarded.get('full_name_choices', [])


def create_form_class(persons):
    full_name_choices = [p.full_name for p in persons]

    class RecordForm(forms.ModelForm):

        full_name = autocomplete.Select2ListChoiceField(
            choice_list=lambda: full_name_choices,
            widget=autocomplete.ListSelect2(
                url='name_autocomplete',
                forward=[
                    forward.Const(
                        full_name_choices,
                        'full_name_choices'
                    )
                ],
            ),
        )

        class Meta:
            model = Record
            fields = ['full_name', 'score']

    return RecordForm


def create_records(request, pk):
    ledger_id = pk
    ledger = Ledger.objects.get(pk=ledger_id)
    persons = Person.objects.filter(ledger_id=ledger_id)

    RecordInlineFormSet = forms.inlineformset_factory(
        Ledger,
        Record,
        can_delete=False,
        extra=len(persons),
        form=create_form_class(list(persons)),
    )

    if request.method == 'POST':
        formset = RecordInlineFormSet(
            request.POST,
            instance=ledger,
        )

        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect('admin')
    else:
        formset = RecordInlineFormSet(
            instance=ledger,
            queryset=Person.objects.none(),
        )
    return render(
        request,
        'app/ledger_detail.html',
        {'formset': formset},
    )
```

**Comment by jpic** [comment]
Perhaps override [create_object()](http://django-autocomplete-light.readthedocs.io/en/master/_modules/dal/views.html#BaseQuerySetView.create_object) ?

**Comment by apnewberry** [comment]
Sorry to bother again!

I am surprised that the above view code gives this choice field (image below) rather than a normal text box. I am able to click on the box and then type below it, but cannot simply `tab` and type in the box. Is this the intended behavior, I'm doing something wrong?

![image](https://user-images.githubusercontent.com/31109952/30045206-a260fa52-91b7-11e7-8b61-a800e4b8eca3.png)

**Comment by jpic** [comment]
I'm not sure, have you checked in select2 issues ?
