### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by tbobm** [yourlabs/django-autocomplete-light#952]
It seems like the `setup.py` is missing the `six` module dependency.

Just in case, I am using `django==2.0` and python3.6.

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fd579d09400>
Traceback (most recent call last):
  File "/srv/project/.venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/srv/project/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/srv/project/.venv/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/project/.venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/srv/project/.venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/project/api/urls.py", line 20, in <module>
    from my_app import views
  File "/srv/project/my_app/views.py", line 6, in <module>
    from dal import autocomplete
  File "/srv/project/.venv/lib/python3.6/site-packages/dal/autocomplete.py", line 48, in <module>
    from dal_select2.views import (
  File "/srv/project/.venv/lib/python3.6/site-packages/dal_select2/views.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

This happened during a fresh and clean install of `dal`

**Comment by jpic** [comment]
Correct ! Can you make a PR so we can include it in next release ? Thanks !
