### ISSUE TITLE
Using DAL with formtools (preview function)

### ISSUE THREAD

**Issue by mogoh** [yourlabs/django-autocomplete-light#960]
Hello.

I am using DAL in combination with the [formtools](https://github.com/django/django-formtools). It works well until I get to the preview page. There the autocomplete widget is gone and just a normal MultipleChoiceField is left (with the previous selected options). If I deselect everything and click preview again, then the autocomplete widget is displayed again.

What can I do?

**Comment by jpic** [comment]
Dunno, perhaps reproduce this in an example app in the test project ?

**Comment by mogoh** [comment]
It is a bit off topic but what I have tried to install the test project (like discribed)[https://django-autocomplete-light.readthedocs.io/en/master/install.html#install-the-demo-project] (with the exception that I used django==1.8), and I get this error message at `./manage.py migrate`

```
  Applying custom_select2.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 232, in create_model
    definition, extra_params = self.column_sql(model, field)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 131, in column_sql
    db_params = field.db_parameters(connection=self.connection)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1989, in db_parameters
    return {"type": self.db_type(connection), "check": []}
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1980, in db_type
    rel_field = self.related_field
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1886, in related_field
    return self.foreign_related_fields[0]
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1620, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields)
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1607, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "/tmp/dal_env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1592, in resolve_related_fields
    raise ValueError('Related model %r cannot be resolved' % self.rel.to)
ValueError: Related model u'select2_foreign_key.TModel' cannot be resolved
```

Is there an easy way to tinker with the test project? Is the manual outdated?

**Comment by jpic** [comment]
We're using Django 2.0, but we're ok with compatibility patches if you want to contribute them.

The problem is that it can't import models because they use the second argument "models.CASCADE" on relations, it's the error i got after playing with test_project on Django 1.8:

```
django.core.exceptions.FieldDoesNotExist: TModel has no field named <function CASCADE at 0x7f4249ba01e0>
```

My recommendation is that you use Django 2.0 for development with the test project.

**Comment by mogoh** [comment]
Ok, so I need to use python 3 (for the test environment) and thus set it in the virtualenv like this: `virtualenv -p python3 dal_env`

**Comment by jpic** [comment]
FYI I'm monitoring this issue on a monitor, feel free to ask as much as you need i'll reply ASAP (currently ongoing a hackaton on another project)

Have fun, make it yours too ;)

**Comment by mogoh** [comment]
Looks like it won't happen today. Thanks for your patience.

**Comment by mogoh** [comment]
I know, I am a bit late, but I think I have a working example. 

https://github.com/mogoh/django-autocomplete-light/blob/960/test_project/select2_preview/preview-test.rst

https://github.com/mogoh/django-autocomplete-light/commit/2712b0b2fdda81d4d025aa7b7672fe9f66c0087c

**Comment by jpic** [comment]
seems to me that the footer block isn't outputed and thus scripts aren't executed

**Comment by jpic** [comment]
it's rendering a tpl without scripts and without footer block, enabling django-debug-toolbar to find more

**Comment by jpic** [comment]
you just need to override formtools/preview.html and install the scripts there (jquery.js and form.media)

and it should work fine

please reopen if any issue

**Comment by mogoh** [comment]
Thank you very much! You solved this riddle for me and that in no time! 😄

**Comment by jpic** [comment]
When users make it easy to reproduce then yes, the problem is when we have to recreate a case it takes more time !
